Update trail.yml

diff --git a/.github/workflows/trail.yml b/.github/workflows/trail.yml
--- a/.github/workflows/trail.yml
+++ b/.github/workflows/trail.yml
@@ -126,7 +126,6 @@ on:
 env:
   username: "${{ github.actor }}"
   branch: "${{ github.event.inputs.branch_name }}"
-  FAILURE_REASON: ""
 
 jobs:
   build:
@@ -144,10 +143,10 @@ jobs:
       run: |
         if [ ! -d "Trail" ]; then
           echo "❌ Failed to navigate to Trail folder. The folder doesn't exist."
-          echo "::set-env name=FAILURE_REASON::Failed to navigate to Trail folder."
+          echo "FAILURE_REASON=Failed to navigate to Trail folder" >> $GITHUB_ENV
           exit 1
         fi
-        cd Trail || { echo "❌ Failed to navigate to Trail folder."; echo "::set-env name=FAILURE_REASON::Failed to navigate to Trail folder."; exit 1; }
+        cd Trail || { echo "❌ Failed to navigate to Trail folder."; echo "FAILURE_REASON=Failed to navigate to Trail folder" >> $GITHUB_ENV; exit 1; }
 
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
@@ -156,11 +155,11 @@ jobs:
 
     - name: Build TrailAutomation.sln
       run: |
-        dotnet build --configuration Release -p:RestorePackages=false "TrailAutomation.sln" || { echo "❌ Build failed."; echo "::set-env name=FAILURE_REASON::Build failed."; exit 1; }
+        dotnet build --configuration Release -p:RestorePackages=false "TrailAutomation.sln" || { echo "❌ Build failed."; echo "FAILURE_REASON=Build failed" >> $GITHUB_ENV; exit 1; }
 
     - name: Execute Regression Test
       run: |
-        dotnet test --logger "trx;LogFileName=test-results.trx" "Trail/TestAutomation/TestAutomation.csproj" || { echo "❌ Regression test failed."; echo "::set-env name=FAILURE_REASON::Regression test failed."; exit 1; }
+        dotnet test --logger "trx;LogFileName=test-results.trx" "Trail/TestAutomation/TestAutomation.csproj" || { echo "❌ Regression test failed."; echo "FAILURE_REASON=Regression test failed" >> $GITHUB_ENV; exit 1; }
 
     - name: Generate Regression Test Report
       id : report
@@ -181,7 +180,7 @@ jobs:
             const issue_number = parseInt('${{ inputs.PR_ISSUE_NUMBER }}');
             const repo_owner = "${{ inputs.PR_REPO_OWNER }}";
             const repo_name = "${{ inputs.PR_REPO_NAME }}";
-            const failureReason = "${{ env.FAILURE_REASON }}";
+            const failureReason = process.env.FAILURE_REASON;
 
             github.rest.issues.createComment({
             issue_number: issue_number,
