Update trail.yml

diff --git a/.github/workflows/trail.yml b/.github/workflows/trail.yml
--- a/.github/workflows/trail.yml
+++ b/.github/workflows/trail.yml
@@ -1,3 +1,110 @@
+# name: Run Project in Trail Folder
+
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       branch_name:
+#         required: true
+#         type: string
+#       PR_ISSUE_NUMBER:
+#         required: true
+#         type: string
+#       PR_REPO_OWNER:
+#         required: true
+#         type: string 
+#       PR_REPO_NAME:
+#         required: true
+#         type: string   
+
+# env:
+#   username: "${{github.actor}}"
+#   branch: "${{ github.event.inputs.branch_name }}"
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+
+#     steps: 
+#     - uses: oNaiPs/secrets-to-env-action@v1
+#       with:
+#         secrets: ${{ toJSON(secrets) }}
+
+#     - name: Checkout  
+#       uses: actions/checkout@v2
+
+#     - name: Navigate to Trail Folder
+#       run: cd Trail
+
+#     - name: Setup .NET Core
+#       uses: actions/setup-dotnet@v1
+#       with:
+#         dotnet-version: 6.0.x
+
+#     - name: Build TrailAutomation.sln
+#       run: dotnet build --configuration Release -p:RestorePackages=false "TrailAutomation.sln"
+
+  
+#     - name: Execute Regression Test
+#       run: dotnet test --logger "trx;LogFileName=test-results.trx" "Trail/TestAutomation/TestAutomation.csproj"
+
+#     - name: Generate Regression Test Report
+#       id : report
+#       uses: dorny/test-reporter@v1
+#       if: always()
+#       with:
+#         name: Regression Test Report
+#         path: "**/test-results.trx"                            
+#         reporter: dotnet-trx     
+#         fail-on-error: true
+    
+#     # - name: Comment on Main PR
+#     #   uses: actions/github-script@v5
+#     #   with:
+#     #     github-token: ${{secrets.PAT_TOKEN}}
+#     #     script: |
+#     #         const issue_number = parseInt('${{ inputs.PR_ISSUE_NUMBER }}');
+#     #         const repo_owner = "${{ inputs.PR_REPO_OWNER }}";
+#     #         const repo_name = "${{ inputs.PR_REPO_NAME }}";
+    
+#     #         github.rest.issues.createComment({
+#     #           issue_number: issue_number,
+#     #           owner: repo_owner,
+#     #           repo: repo_name,
+#     #            body: `🎉 Live ENV Test Results 🎉
+
+#     #                   ✅ Passed: ${{ steps.report.outputs.passed }}
+#     #                   ❌ Failed: ${{ steps.report.outputs.failed }}
+#     #                   ⏭️ Skipped: ${{ steps.report.outputs.skipped }}
+                      
+#     #                   Keep up the good work! 👍`
+#     #         })
+#     - name: Comment on Failure
+#       if: failure()
+#       uses: actions/github-script@v5
+#       with:
+#           github-token: ${{ secrets.PAT_TOKEN }}
+#           script: |
+#             const issue_number = parseInt('${{ inputs.PR_ISSUE_NUMBER }}');
+#             const repo_owner = "${{ inputs.PR_REPO_OWNER }}";
+#             const repo_name = "${{ inputs.PR_REPO_NAME }}";
+
+#             github.rest.issues.createComment({
+#             issue_number: issue_number,
+#             owner: repo_owner,
+#             repo: repo_name,
+#             body: ```
+#                 ❌ Failed in Trail ENV Workflow 🚨
+    
+#                 There was a failure in the Trail environment workflow.
+    
+#                 You can view the workflow run [here](https://github.com/${repo_owner}/test/actions/runs/${{ github.run_id }}).
+    
+#                 Please investigate and address the issue.
+#                 ```
+#             })
+
+
+
 name: Run Project in Trail Folder
 
 on:
@@ -33,7 +140,12 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Navigate to Trail Folder
-      run: cd Trail
+      run: |
+        if [ ! -d "Trail" ]; then
+          echo "❌ Failed to navigate to Trail folder. The folder doesn't exist."
+          exit 1
+        fi
+        cd Trail || { echo "❌ Failed to navigate to Trail folder."; exit 1; }
 
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
@@ -41,11 +153,10 @@ jobs:
         dotnet-version: 6.0.x
 
     - name: Build TrailAutomation.sln
-      run: dotnet build --configuration Release -p:RestorePackages=false "TrailAutomation.sln"
+      run: dotnet build --configuration Release -p:RestorePackages=false "TrailAutomation.sln" || { echo "❌ Build failed."; exit 1; }
 
-  
     - name: Execute Regression Test
-      run: dotnet test --logger "trx;LogFileName=test-results.trx" "Trail/TestAutomation/TestAutomation.csproj"
+      run: dotnet test --logger "trx;LogFileName=test-results.trx" "Trail/TestAutomation/TestAutomation.csproj" || { echo "❌ Regression test failed."; exit 1; }
 
     - name: Generate Regression Test Report
       id : report
@@ -56,28 +167,7 @@ jobs:
         path: "**/test-results.trx"                            
         reporter: dotnet-trx     
         fail-on-error: true
-    
-    # - name: Comment on Main PR
-    #   uses: actions/github-script@v5
-    #   with:
-    #     github-token: ${{secrets.PAT_TOKEN}}
-    #     script: |
-    #         const issue_number = parseInt('${{ inputs.PR_ISSUE_NUMBER }}');
-    #         const repo_owner = "${{ inputs.PR_REPO_OWNER }}";
-    #         const repo_name = "${{ inputs.PR_REPO_NAME }}";
-    
-    #         github.rest.issues.createComment({
-    #           issue_number: issue_number,
-    #           owner: repo_owner,
-    #           repo: repo_name,
-    #            body: `🎉 Live ENV Test Results 🎉
 
-    #                   ✅ Passed: ${{ steps.report.outputs.passed }}
-    #                   ❌ Failed: ${{ steps.report.outputs.failed }}
-    #                   ⏭️ Skipped: ${{ steps.report.outputs.skipped }}
-                      
-    #                   Keep up the good work! 👍`
-    #         })
     - name: Comment on Failure
       if: failure()
       uses: actions/github-script@v5
@@ -92,13 +182,17 @@ jobs:
             issue_number: issue_number,
             owner: repo_owner,
             repo: repo_name,
-            body: ```
+            body: `
                 ❌ Failed in Trail ENV Workflow 🚨
-    
+
                 There was a failure in the Trail environment workflow.
-    
+
                 You can view the workflow run [here](https://github.com/${repo_owner}/test/actions/runs/${{ github.run_id }}).
-    
+                
+                Error Reason:
+                {{ failureReason }}
+
                 Please investigate and address the issue.
-                ```
+                `
             })
+
