Update trail.yml

diff --git a/.github/workflows/trail.yml b/.github/workflows/trail.yml
--- a/.github/workflows/trail.yml
+++ b/.github/workflows/trail.yml
@@ -124,8 +124,9 @@ on:
         type: string   
 
 env:
-  username: "${{github.actor}}"
+  username: "${{ github.actor }}"
   branch: "${{ github.event.inputs.branch_name }}"
+  FAILURE_REASON: ""
 
 jobs:
   build:
@@ -143,9 +144,10 @@ jobs:
       run: |
         if [ ! -d "Trail" ]; then
           echo "❌ Failed to navigate to Trail folder. The folder doesn't exist."
+          echo "::set-env name=FAILURE_REASON::Failed to navigate to Trail folder."
           exit 1
         fi
-        cd Trail || { echo "❌ Failed to navigate to Trail folder."; exit 1; }
+        cd Trail || { echo "❌ Failed to navigate to Trail folder."; echo "::set-env name=FAILURE_REASON::Failed to navigate to Trail folder."; exit 1; }
 
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
@@ -153,10 +155,12 @@ jobs:
         dotnet-version: 6.0.x
 
     - name: Build TrailAutomation.sln
-      run: dotnet build --configuration Release -p:RestorePackages=false "TrailAutomation.sln" || { echo "❌ Build failed."; exit 1; }
+      run: |
+        dotnet build --configuration Release -p:RestorePackages=false "TrailAutomation.sln" || { echo "❌ Build failed."; echo "::set-env name=FAILURE_REASON::Build failed."; exit 1; }
 
     - name: Execute Regression Test
-      run: dotnet test --logger "trx;LogFileName=test-results.trx" "Trail/TestAutomation/TestAutomation.csproj" || { echo "❌ Regression test failed."; exit 1; }
+      run: |
+        dotnet test --logger "trx;LogFileName=test-results.trx" "Trail/TestAutomation/TestAutomation.csproj" || { echo "❌ Regression test failed."; echo "::set-env name=FAILURE_REASON::Regression test failed."; exit 1; }
 
     - name: Generate Regression Test Report
       id : report
@@ -177,6 +181,7 @@ jobs:
             const issue_number = parseInt('${{ inputs.PR_ISSUE_NUMBER }}');
             const repo_owner = "${{ inputs.PR_REPO_OWNER }}";
             const repo_name = "${{ inputs.PR_REPO_NAME }}";
+            const failureReason = "${{ env.FAILURE_REASON }}";
 
             github.rest.issues.createComment({
             issue_number: issue_number,
@@ -187,12 +192,11 @@ jobs:
 
                 There was a failure in the Trail environment workflow.
 
-                You can view the workflow run [here](https://github.com/${repo_owner}/test/actions/runs/${{ github.run_id }}).
-                
                 Error Reason:
-                {{ failureReason }}
+                ${failureReason}
+
+                You can view the workflow run [here](https://github.com/${repo_owner}/test/actions/runs/${{ github.run_id }}).
 
                 Please investigate and address the issue.
                 `
             })
-
